import utils_3D

# Container 1A (cm and litter)
CONTAINER_WIDTH = 233
CONTAINER_HEIGHT = 220
CONTAINER_DEPTH = 1200
CONTAINER_LOAD_3D = (CONTAINER_WIDTH * CONTAINER_HEIGHT * CONTAINER_DEPTH) / 100 # litter

# Pallet EUR 1 (cm and litter)
PALLET_WIDTH = 120
PALLET_DEPTH = 80
PALLET_HEIGHT = CONTAINER_HEIGHT - 145  # 145 is the height of the pallet itself
PALLET_LOAD = (PALLET_WIDTH * PALLET_DEPTH * PALLET_HEIGHT) / 100

PALLET_DIMS3D = utils_3D.Dimension(PALLET_WIDTH, 
                                   PALLET_DEPTH, 
                                   PALLET_HEIGHT, 
                                   PALLET_LOAD)

# Product dimension ranges (mm and kg)
NUM_PRODUCTS = int(1e6)
MIN_PRODUCT_WIDTH = 50
MAX_PRODUCT_WIDTH = PALLET_WIDTH
MIN_PRODUCT_DEPTH = 50
MAX_PRODUCT_DEPTH = PALLET_DEPTH
MIN_PRODUCT_HEIGHT = 50
MAX_PRODUCT_HEIGHT = PALLET_HEIGHT
#MIN_PRODUCT_WEIGHT = 2
#MAX_PRODUCT_WEIGHT = PALLET_LOAD

# Numpy
RANDOM_SEED = 42
